# Generated by Django 5.0.8 on 2024-10-18 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(default='blog1.jpeg', upload_to='blog/')),
                ('intro', models.TextField()),
                ('category', models.CharField(max_length=100, null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
